export const cardData = [
    {
      title: "Fast Delivery",
      img: "/success1.webp",
      desc: "Quick and secure delivery services at your doorstep.",
      like: 150,
      comment: 50,
      share: 40,
      aos: "zoom-in",
    },
    {
      title: "Premium Quality",
      img: "/success2.webp",
      desc: "Top-notch quality products with guaranteed satisfaction.",
      like: 120,
      comment: 35,
      share: 30,
      aos: "fade-up",
    },
    {
      title: "24/7 Support",
      img: "/success3.webp",
      desc: "Round-the-clock customer support for all your queries.",
      like: 200,
      comment: 80,
      share: 55,
      aos: "fade-down",
    },
    {
      title: "Affordable Prices",
      img: "/success4.webp",
      desc: "Best prices in the market with high value for money.",
      like: 180,
      comment: 70,
      share: 50,
      aos: "zoom-in-up",
    },
    {
      title: "Eco-Friendly",
      img: "/success5.webp",
      desc: "Sustainable and environmentally friendly products.",
      like: 140,
      comment: 40,
      share: 35,
      aos: "flip-left",
    },
    {
      title: "Secure Payments",
      img: "/success6.webp",
      desc: "Highly secure transactions with encrypted payments.",
      like: 160,
      comment: 55,
      share: 45,
      aos: "flip-right",
    },
  ];
  