export const successData =  [
  {
    title: "Achieve Excellence",
    img: "/logo.webp",
    desc: "Success is built on consistency and continuous improvement.",
    points: ["✅ Hard Work Pays Off", "✅ Stay Focused", "✅ Set Clear Goals", "✅ Learn from Failures"],
    gradient: "from-purple-500 via-pink-500 to-red-500",
    imgBg: "bg-white/10 backdrop-blur-md",
  },
  {
    title: "Innovate and Lead",
    img: "/img2.webp",
    desc: "Innovation is key to staying ahead in any field.",
    points: ["✅ Think Outside the Box", "✅ Challenge the Norm", "✅ Take Calculated Risks", "✅ Be a Problem Solver"],
    gradient: "from-blue-500 via-cyan-500 to-teal-500",
    imgBg: "bg-blue-400/20 backdrop-blur-lg",
  },
  {
    title: "Stay Determined",
    img: "/img3.webp",
    desc: "Determination fuels success, even in tough times.",
    points: ["✅ Never Give Up", "✅ Believe in Yourself", "✅ Adapt to Change", "✅ Stay Motivated"],
    gradient: "from-green-500 via-lime-500 to-yellow-500",
    imgBg: "bg-green-400/20 backdrop-blur-md",
  },
  {
    title: "Smart Work Matters",
    img: "/img4.webp",
    desc: "Hard work combined with smart strategies leads to success.",
    points: ["✅ Prioritize Tasks", "✅ Automate & Delegate", "✅ Work-Life Balance", "✅ Continuous Learning"],
    gradient: "from-red-500 via-orange-500 to-yellow-500",
    imgBg: "bg-orange-400/20 backdrop-blur-lg",
  },
  {
    title: "Networking is Power",
    img: "/img5.webp",
    desc: "Building relationships opens doors to new opportunities.",
    points: ["✅ Meet New People", "✅ Share Your Ideas", "✅ Learn from Experts", "✅ Build Your Reputation"],
    gradient: "from-indigo-500 via-purple-500 to-pink-500",
    imgBg: "bg-purple-400/20 backdrop-blur-md",
  },
  {
    title: "Consistency Wins",
    img: "/img6.webp",
    desc: "Small daily improvements lead to incredible results.",
    points: ["✅ Stay Committed", "✅ Create Habits", "✅ Track Your Progress", "✅ Celebrate Small Wins"],
    gradient: "from-emerald-500 via-teal-500 to-blue-500",
    imgBg: "bg-teal-400/20 backdrop-blur-lg",
  },
  {
    title: "Leadership & Growth",
    img: "/img7.webp",
    desc: "Great leaders inspire and drive growth for themselves and others.",
    points: ["✅ Lead by Example", "✅ Empower Others", "✅ Take Responsibility", "✅ Keep Learning"],
    gradient: "from-gray-900 via-gray-700 to-gray-500",
    imgBg: "bg-gray-400/20",
  },
];